version: '3'

volumes:
  postgres_volume:
  redis_volume:

services:

  pg-local:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
